version: '3.8'

services:
  # API Service
  api:
    build: .
    ports:
      - "8080:8000"  # Changed from 8000:8000 to avoid port conflict
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - GRAPHDB_URL=http://graphdb:7200/repositories/CHeVIE
      - KAFKA_BROKERS=kafka:9092
      - DASK_SCHEDULER=dask-scheduler:8786
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - .env
    depends_on:
      - redis
      - graphdb
      - worker
      - kafka
      - dask-scheduler
      - qdrant
      - elasticsearch

  # Celery Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - GRAPHDB_URL=http://graphdb:7200/repositories/CHeVIE
      - KAFKA_BROKERS=kafka:9092
      - DASK_SCHEDULER=dask-scheduler:8786
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file:
      - .env
    depends_on:
      - redis
      - graphdb
      - kafka
      - dask-scheduler
      - qdrant
      - elasticsearch

  # Redis for caching and message broker
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./docker-config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # GraphDB
  graphdb:
    image: ontotext/graphdb:10.6.4
    ports:
      - "7200:7200"
    volumes:
      - ./data/graphdb:/opt/graphdb/home
      - ./data/ontologies:/root/ontologies
      - ./config/graphdb/cluster-config.ttl:/opt/graphdb/conf/cluster-config.ttl
    tmpfs:
      - /opt/graphdb/home/work/tmp

  # Kong API Gateway
  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_CONF=/usr/local/kong/kong.conf
    ports:
      - "8002:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./config/kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ./config/kong/kong.conf:/usr/local/kong/kong.conf
    depends_on:
      - api

  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 1
      ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: 3
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    command: >
      sh -c "
        echo 'Starting ZooKeeper with clean state' &&
        rm -rf /var/lib/zookeeper/data/* &&
        /etc/confluent/docker/run"
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    command: >
      bash -c '
        echo "Giving ZooKeeper time to start" &&
        sleep 15 &&
        echo "Clearing Kafka data directory" &&
        rm -rf /var/lib/kafka/data/* &&
        echo "Starting Kafka" &&
        /etc/confluent/docker/run'
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/metadata
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-metadata:/var/lib/kafka/metadata
    depends_on:
      - zookeeper

  # Dask cluster
  dask-scheduler:
    image: daskdev/dask:latest
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  dask-worker:
    image: daskdev/dask:latest
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
    environment:
      - DASK_SCHEDULER=dask-scheduler:8786
    depends_on:
      - dask-scheduler

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - ./docker-config/grafana-config.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./docker-config/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana

  # Ray cluster
  ray-head:
    image: rayproject/ray:latest
    ports:
      - "8265:8265"   # Dashboard
      - "10001:10001" # Client
    command: >
      /bin/bash -c "
        mkdir -p /tmp/ray && 
        chmod 777 /tmp/ray && 
        rm -rf /tmp/ray/* &&
        ray start --head --dashboard-host=0.0.0.0 --num-cpus=1 --include-dashboard=true --dashboard-port=8265 --port=6379"
    environment:
      - RAY_ADDRESS=ray-head:6379
      # Remove ping_gcs_rpc_server_max_retries that causes configuration error
    volumes:
      - ray-temp:/tmp/ray
    user: "0:0"  # Run as root to ensure proper permissions
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  ray-worker:
    image: rayproject/ray:latest
    command: >
      /bin/bash -c "
        mkdir -p /tmp/ray && 
        chmod 777 /tmp/ray && 
        rm -rf /tmp/ray/* &&
        sleep 30 &&
        ray start --address=ray-head:6379 --num-cpus=1"
    environment:
      - RAY_ADDRESS=ray-head:6379
    depends_on:
      - ray-head
    volumes:
      - ray-temp:/tmp/ray
    user: "0:0"  # Run as root to ensure proper permissions
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_FULL_TEXT_SEARCH=true

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  redis-data:
  kafka-data:
  kafka-metadata:
  zookeeper-data:
  prometheus-data:
  grafana-data:
  ray-temp:
  qdrant-data:
  elasticsearch_data:
