_format_version: "2.1"
_transform: true

services:
  - name: nl2sparql-api
    url: http://api:8000
    routes:
      - name: api-route
        paths:
          - /api
    plugins:
      - name: prometheus
        config:
          status_code_metrics: true
          latency_metrics: true
          upstream_health_metrics: true

consumers:
  - username: api-user
