apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl2sparql-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nl2sparql-api
  template:
    metadata:
      labels:
        app: nl2sparql-api
    spec:
      containers:
      - name: api
        image: nl2sparql-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/1"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/2"
        - name: GRAPHDB_URL
          value: "http://graphdb:7200/repositories/CHeVIE"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"