apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl2sparql-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nl2sparql-worker
  template:
    metadata:
      labels:
        app: nl2sparql-worker
    spec:
      containers:
      - name: worker
        image: nl2sparql-worker:latest
        imagePullPolicy: IfNotPresent  # Use local image if available
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/1"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/2"
        - name: GRAPHDB_URL
          value: "http://graphdb:7200/repositories/CHeVIE"
        - name: QDRANT_URL
          value: "http://qdrant:6333"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "4Gi"
            cpu: "1"